import { PlaceHolderImages } from "./placeholder-images";

export type Blog = {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string; // Stored as HTML for this mock
  imageUrl: string;
  tags: string[];
};

export const mockBlogs: Blog[] = [
  {
    id: '1',
    title: 'How to Optimize for Google’s AI Overviews',
    slug: 'how-to-optimize-for-googles-ai-overviews',
    excerpt: 'Learn how AEO optimization helps your content appear in AI Overviews and featured snippets. A deep dive into the new age of search.',
    content: `
      <p>The world of SEO is changing faster than ever, and at the forefront of this evolution are Google's AI Overviews. These AI-generated summaries appear at the top of search results, often replacing the traditional "position zero" featured snippet. To stay competitive, you must adapt your strategy for Answer Engine Optimization (AEO).</p>
      <h2 class="text-2xl font-bold my-4">What Are AI Overviews?</h2>
      <p>AI Overviews are comprehensive, conversational answers generated by Google's large language models. They synthesize information from multiple high-ranking pages to provide a direct answer to a user's query, eliminating the need for them to click through to different websites.</p>
      <blockquote class="border-l-4 border-accent p-4 my-4 bg-secondary/50">
        "Getting into an AI Overview is the new #1 ranking."
      </blockquote>
      <h2 class="text-2xl font-bold my-4">Key AEO Strategies for AI Overviews</h2>
      <p>Optimizing for these snippets requires a shift in mindset from keywords to concepts, and from pages to answers.</p>
      <ul class="list-disc list-inside space-y-2 my-4">
        <li><strong>Provide Clear, Concise Answers:</strong> Structure your content to answer specific questions directly. Use headings for questions and provide the answer immediately below.</li>
        <li><strong>Use Structured Data:</strong> Implement schema markup like FAQPage, HowTo, and QAPage to give search engines explicit information about your content's structure.</li>
        <li><strong>Focus on E-E-A-T:</strong> Demonstrate Experience, Expertise, Authoritativeness, and Trustworthiness. This is more important than ever.</li>
        <li><strong>Write in a Natural, Conversational Tone:</strong> Write for humans, not just bots. AI models are trained to prefer content that reads naturally.</li>
      </ul>
      <p>By focusing on these AEO principles, you not only increase your chances of being featured in AI Overviews but also create better, more user-friendly content overall.</p>
    `,
    imageUrl: PlaceHolderImages[0].imageUrl,
    tags: ['AEO', 'Google AI', 'SEO'],
  },
  {
    id: '2',
    title: 'The Ultimate Guide to Featured Snippet Optimization',
    slug: 'ultimate-guide-featured-snippet-optimization',
    excerpt: 'A step-by-step guide to winning more featured snippets. From paragraph snippets to lists and tables, we cover it all.',
    content: `
      <p>Featured snippets are the holy grail of SEO. They offer immense visibility and can significantly boost your click-through rate. Here’s how to claim them.</p>
      <h2 class="text-2xl font-bold my-4">Types of Featured Snippets</h2>
      <ul class="list-disc list-inside space-y-2 my-4">
        <li><strong>Paragraph Snippets:</strong> The most common type, offering a short, direct answer. Aim for 40-60 words.</li>
        <li><strong>Bulleted/Numbered Lists:</strong> Perfect for "how-to" guides or step-by-step instructions.</li>
        <li><strong>Table Snippets:</strong> Ideal for data comparisons. Google can pull data from your page and create its own table.</li>
      </ul>
      <p>The key is to identify "snippet-worthy" queries and structure your content to provide the best possible answer in the most digestible format.</p>
    `,
    imageUrl: PlaceHolderImages[1].imageUrl,
    tags: ['Featured Snippets', 'SEO', 'Content Strategy'],
  },
  {
    id: '3',
    title: 'Why Structured Data is Crucial for Modern SEO',
    slug: 'why-structured-data-is-crucial-for-modern-seo',
    excerpt: 'Schema markup is your content’s translator for search engines. Understand why it’s no longer optional for serious content creators.',
    content: `
      <p>If content is king, structured data is its interpreter. Schema markup is a vocabulary that you add to your website's HTML to help search engines understand your content more effectively.</p>
      <h2 class="text-2xl font-bold my-4">Benefits of Using Schema</h2>
      <ul class="list-disc list-inside space-y-2 my-4">
        <li><strong>Enhanced SERP Appearance:</strong> Unlock rich results like star ratings, event schedules, and FAQ dropdowns.</li>
        <li><strong>Improved Relevancy Signals:</strong> Tell Google exactly what your content is about, from an article to a recipe.</li>
        <li><strong>Future-Proofs Your Content:</strong> As search becomes more semantic, structured data will only grow in importance for voice search and AI answers.</li>
      </ul>
      <p>Start with simple schemas like Article, FAQPage, and Person. Tools like our own Schema Generator can make this process painless.</p>
    `,
    imageUrl: PlaceHolderImages[2].imageUrl,
    tags: ['Schema', 'Technical SEO', 'JSON-LD'],
  },
];
